"""Completei tabela de clientes

Revision ID: 129224cd1213
Revises: 45ad2c6923aa
Create Date: 2020-06-22 17:31:17.100475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129224cd1213'
down_revision = '45ad2c6923aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('datainsercao', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('email', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('endereco', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('prospeccao', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('status', sa.String(), nullable=False))
    op.add_column('cliente', sa.Column('telefone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'telefone')
    op.drop_column('cliente', 'status')
    op.drop_column('cliente', 'prospeccao')
    op.drop_column('cliente', 'endereco')
    op.drop_column('cliente', 'email')
    op.drop_column('cliente', 'datainsercao')
    # ### end Alembic commands ###
