"""Observacoes de cliente

Revision ID: 75f0b6abe515
Revises: f21d81a4da79
Create Date: 2020-06-19 16:41:15.026400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f0b6abe515'
down_revision = 'f21d81a4da79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('observacoes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'observacoes')
    # ### end Alembic commands ###
